### ISSUE TITLE
Create a POS Simulator UI to be integrated with the backend APIs

### ISSUE THREAD

**Issue by BrendonButler** [BrendonButler/WorkWiz#1]
Create a Point of Sale (POS) UI system to take inputs and build a cart that will be eventually "purchasable." The UI will hook into the backend REST APIs to collect products and product data (pricing, name, description, etc.).

### TODO
- [x] Create a React UI component 
  - [x] Needs a text input field to take UPCs, Product names, SKUs that will be added to the cart
  - [x] Needs a shopping basket component that lists the products and has the ability to remove items or add more quantity
