### ISSUE TITLE
Connect the React frontend to the Spring backend using API endpoints

### ISSUE THREAD

**Issue by BrendonButler** [BrendonButler/WorkWiz#6]
The Point of Sale (POS) simulator should search items using the Spring RESTful APIs that are connected to the database of shopping items.

**Todo:**

- [x] Create a ShoppingItem interface in TypeScript for the React application
- [x] Update the Pos component to query the shopping items search endpoint
- [x] Add pricing to the Pos component UI
- [x] Utilize tooltips for the shopping item's description
